server:
  port: 8080
  servlet:
    context-path: /com.company.book

#Database
spring:
  jpa:
    properties:
      hibernate.default_schema: bookapi
      hibernate.dialect : org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy : org.hibernate.cfg.ImproveNamingStrategy
  datasource:
    url: jdbc:mysql://localhost:8889/bookapi
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    testWhileIdle : true
    validationQuery : SELECT 1
     

#MySQL properties


#Hibernate properties
